version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/usr/share/nginx/html
    depends_on:
      - express
    networks:
      - my-network  # ระบุเครือข่ายที่ถูกต้อง

  express:
    build:
      context: ./express-docker-project
    container_name: express-container
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb-container:27017/your_database_name  # ปรับ MONGODB_URI ให้สมบูรณ์
    networks:
      - my-network  # ระบุเครือข่ายที่ถูกต้อง

  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network  # ระบุเครือข่ายที่ถูกต้อง

volumes:
  mongo-data:
    driver: local

networks:
  my-network:
    driver: bridge  # กำหนด driver ให้ถูกต้อง

